## 09. 예외 처리하기와 미루기

### try~catch 문

- try 블록에는 예외가 발생할 가능성이 있는 코드를 작성하고 try 블록 안에서 예외가 발생하는 경우 catch 블록이 수행된다.

![Untitled](https://t1.daumcdn.net/cafeattach/1Dzpp/34db70e72a7d74a3406e6feafe3615dea7100fa8)

- 프로그래머가 예외를 처리해줘야 하는 예 (배열의 오류 처리)

```java
public class ArrayIndexExceptionHandling {
    public static void main(String[] args) {

        int[] arr = {1,2,3,4,5};

        for (int i= 0; i <= 5; i++) {
            // length가 5이면 index는 4까지인데 5를 가리키고 있어서 에러가 났다. i<=5
            System.out.println(arr[i]);
        }

        System.out.println("비정상 종료되지 않았습니다.");
        System.out.println("hello!");
    }
}
```

- 결과

![9.png](https://t1.daumcdn.net/cafeattach/1Dzpp/89caa9bb5267851d9f3a65ac720ec1f43fac1f92)

- 예외 처리

```java
public class ArrayIndexExceptionHandling {
    public static void main(String[] args) {

        int[] arr = {1,2,3,4,5};

        try {
            for (int i = 0; i <= 5; i++) {
                // length가 5이면 index는 4까지인데 5를 가리키고 있어서 에러가 났다. i<=5
                System.out.println(arr[i]);
            }
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Index "+e.getMessage() + " out of bounds for length "+ e.getMessage());
            System.out.println(e.toString());
        }

        System.out.println("비정상 종료되지 않았습니다.");
        System.out.println("hello!");
    }
}
```

- 결과

![1.png](https://t1.daumcdn.net/cafeattach/1Dzpp/411b0321692aa83e86361a393c09f7f413ad7a83)

### try~catch~finally 문

- finally 블럭에서 파일을 닫거나 네트워크를 닫는 등의 리소스 해제 구현을 한다.
- try{} 블럭이 수행된는 경우, finally{} 블럭은 항상 수행 된다.
- 여러 개의 예외 블럭이 있는 경우 각각에서 리소스를 해제하지 않고 finally블럭에서 해제하도록 구현한다.
- 컴파일러에 의해 예외가 처리 되는 예 (파일 에러 처리)

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class FileExceptionHandling {
    public static void main(String[] args) {

        FileInputStream fis = null;

        try {
            fis = new FileInputStream("FileTest.txt");
            System.out.println("read");

            // try-catch 구문안에 또 다른 try-catch 양식이 지저분하다.
//            try {
//                fis.close();
//            } catch (IOException e) {
//                e.printStackTrace();
//            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
           // return;
//            try {
//                fis.close();
//            } catch (IOException ex) {
//                ex.printStackTrace();
//            }
            // finally 구문은 결과에 상관없이 항상 걸리다.
        } finally {
            if(fis != null) {
                try {
                    fis.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
                System.out.println("finally!");
        }
        System.out.println("end");
    }
}
```

- 결과

![3.png](https://t1.daumcdn.net/cafeattach/1Dzpp/6470f49c7c3aa6c58e530d572ad3c70136086027)

- 파일이 없을 경우 에러!

![9.png](https://t1.daumcdn.net/cafeattach/1Dzpp/f50d6bebf436a1ff448c68320918b9b51fba65e4)

- 최종 수정 코드

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class FileExceptionHandling {
    public static void main(String[] args) {

        // FileInputStream fis = null;

        // 이렇게 선언 시 자동으로 close된다. AutoCloseable하게 선언
        try (FileInputStream fis = new FileInputStream("FileTest.txt")) {
            System.out.println("read");

            // 읽을 때 예외.
        } catch (FileNotFoundException e) {
            e.printStackTrace();

            // close될 때 예외.
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("end");
    }
}
```

- 결과

![6.png](https://t1.daumcdn.net/cafeattach/1Dzpp/f8d6d2533eecf98c5840e741c1dcc64ee08e7553)

### try-with-resources문

- 리소스를 사용하는 경우 close() 하지 않아도 자동으로 해제 되도록 한다.
- 자바 7부터 제공되는 구문
- 리소스를 try() 내부에서 선언해야만한다.
- close()를 명시적으로 호출하지 않아도 try{}블록에서 열린 리소스는 정상적인 경우나 예외가 발생한 경우 모두 자동으로 해제된다.
- 해당 리소스 클래스가 AutoCloseable 인터페이스를 구현 해야 한다.
- FileInputStream의 경우에는 AutoCloseable을 구현하고 있다.
- 자바 9 부터 리소스는 try() 외부에서 선언하고 변수만을 try(obj) 와 같이 사용할 수 있다.

![Untitled](https://t1.daumcdn.net/cafeattach/1Dzpp/4273254320c6c9602932a32d26918facbe622999)

- AutoCloseable인터페이스 구현 실습

```java
public class AutoCloseableObj implements AutoCloseable{

    @Override
    public void close() throws Exception {
        System.out.println("closing....");
    }
}
```

```java
public class AutoCloseTest {
    public static void main(String[] args) {

       AutoCloseObj obj = new AutoCloseObj();

        try /*(obj)*/ {
            throw new Exception();

        } catch (Exception e) {
            System.out.println("exception~");
        }

        System.out.println("end");
    }
}
```

### 예외 처리 미루기

- 예외 처리는 예외가 발생하는 문장에서 try~catch 블록으로 처리하는 방법과 이를 사용하는 부분에서 처리하는 방법 두 가지가 있다
- throws를 이용하면 예외가 발생할 수 있는 부분을 사용하는 문장에서 예외를 처리할 수 있다.

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ThrowsException {
                                                        // throws : 예외를 미루겠다.
    public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
        // 예외는 이 메서드 안에서 일어 날 수 있지만, 핸들링은 수행문에서 하지 않고 메서드를 쓰는 쪽에서 핸들링 하겠다.

        FileInputStream fis = new FileInputStream(fileName);

        Class c = Class.forName(className);
        return c;
    }

    public static void main(String[] args) {

        ThrowsException test = new ThrowsException();

        try {
            test.loadClass("FileTest1.txt", "abc");
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }
        System.out.println("end");
    }
}
```

- FileNotFoundException 결과

![2.png](https://t1.daumcdn.net/cafeattach/1Dzpp/d2d164bebc315848ec20184cad3057fe72a3fe8f)

- ClassNotFoundException 결과

![1.png](https://t1.daumcdn.net/cafeattach/1Dzpp/10c9e44967cd31c87eb43bfe3590711ec21eab3f)

### 하나의 try{}블록에서 예외가 여러개 발생하는 경우

- 여러개의 예외가 발생하는 경우 예외를 묶어서 하나의 방법으로 처리할 수도 있다.

```java
try {
	test.loadClass("FileTest.txt", "abc");
} catch (ClassNotFoundException | FileNotFoundException e) {
  System.out.println(e);
}
```

- 각각의 예외를 따로 처리할 수도 있다.

```java
try {
  test.loadClass("FileTest.txt", "abc");
} catch (ClassNotFoundException | FileNotFoundException e) {
  System.out.println(e);
} catch (FileNotFoundException e) {
  System.out.println(e);
} catch (ClassNotFoundException e) {
  System.out.println(e);
} catch (Exception e) {  // 최상위 예외 처리. 모든 익셉션의 디폴트. 맨 처음에 쓰면 안된다.
	System.out.println(e);
}
```

- Exception 클래스를 활용하여 defualt 처리를 할 때 Exception 블록은 맨 마지막에 위치해야 한다.